//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullet_Dungeon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bullet_Dungeon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;obstacles&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;475&lt;/x&gt;
        ///		&lt;y&gt;425&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;200&lt;/x&gt;
        ///		&lt;y&gt;475&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;4&lt;/hp&gt;
        ///		&lt;type&gt;box&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;1620&lt;/x&gt;
        ///		&lt;y&gt;475&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;4&lt;/hp&gt;
        ///		&lt;type&gt;box&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;660&lt;/x&gt;
        ///		&lt;y&gt;200&lt;/y&gt;
        ///		&lt;width&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;obstacles&gt;
        ///
        ///	side walls
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;200&lt;/x&gt;
        ///		&lt;y&gt;220&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;600&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;1620&lt;/x&gt;
        ///		&lt;y&gt;220&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;600&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///
        ///	bottom boxes
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;660&lt;/x&gt;
        ///		&lt;y&gt;700&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;4&lt;/hp&gt;
        ///		&lt;type&gt;box&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;obstacles&gt;
        ///	middle walls
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;475&lt;/x&gt;
        ///		&lt;y&gt;475&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;475&lt;/x&gt;
        ///		&lt;y&gt;775&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;475&lt;/x&gt;
        ///		&lt;y&gt;175&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;100&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	
        ///	boxes
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;180 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;obstacles&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;150&lt;/x&gt;
        ///		&lt;y&gt;800&lt;/y&gt;
        ///		&lt;width&gt;125&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;obstacle&gt;
        ///		&lt;x&gt;1645&lt;/x&gt;
        ///		&lt;y&gt;800&lt;/y&gt;
        ///		&lt;width&gt;125&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/height&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;type&gt;wall&lt;/type&gt;
        ///	&lt;/obstacle&gt;
        ///	&lt;enemy&gt;
        ///		&lt;enemyType&gt;Boss&lt;/enemyType&gt;
        ///		&lt;enemyX&gt;800&lt;/enemyX&gt;
        ///		&lt;enemyY&gt;100&lt;/enemyY&gt;
        ///	&lt;/enemy&gt;
        ///&lt;/obstacles&gt;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steel1 {
            get {
                object obj = ResourceManager.GetObject("Steel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steel2 {
            get {
                object obj = ResourceManager.GetObject("Steel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steel3 {
            get {
                object obj = ResourceManager.GetObject("Steel3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
